### 服务名称
spring:
  application:
    name: eureka-cluster

### 服务端口号
server:
  port: 8101


### Eureka配置
eureka:
  instance:
    ### 注册中心IP地址
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/
    #### 是否将当前项目注册到注册中心
    register-with-eureka: true
    #### 自己为注册中心，不需要去检索服务信息
    fetch-registry: true

